#!/usr/bin/env python3
"""Generate gm-bank.h, the General MIDI FM instrument set, from ScummVM's AdLib driver.

usage: extract-gm-bank.py <scummvm>/audio/adlib.cpp > gm-bank.h

The tables (g_gmInstruments, g_gmPercussionInstruments and the percussion key
map) are ScummVM's, GPL-3.0-or-later; the generated header keeps that notice.
Run this only to regenerate the header: the committed gm-bank.h is what builds.
Each instrument keeps the fields the OPL2 needs, in ScummVM's own encoding:
the attack/decay and sustain/release bytes are stored inverted, and the high
bits of each waveform byte hold the velocity sensitivity.
"""
import re
import sys

source = open(sys.argv[1], encoding="utf-8", errors="replace").read()


def table(name):
    start = source.index(name)
    start = source.index("{", source.index("=", start))
    depth, i = 0, start
    while True:
        depth += {"{": 1, "}": -1}.get(source[i], 0)
        i += 1
        if depth == 0:
            break
    return source[start:i]


def instruments(body):
    rows = []
    for match in re.finditer(r"\{\s*((?:0x[0-9A-Fa-f]{2}|\d+)\s*,[^{}]*?)\{[^{}]*\}\s*,\s*(\d+)\s*,\s*\{[^{}]*\}\s*,\s*(0x[0-9A-Fa-f]{2}|\d+)\s*\}", body):
        head = [int(x, 0) for x in match.group(1).replace("\n", " ").split(",") if x.strip()]
        rows.append(head[:11] + [int(match.group(3), 0)])
    return rows


melodic = instruments(table("g_gmInstruments[128]"))
percussion = instruments(table("g_gmPercussionInstruments[39]"))
keymap = [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]{2}", table("g_gmPercussionInstrumentMap[128]"))]
assert len(melodic) == 128, len(melodic)
assert len(percussion) == 39, len(percussion)
assert len(keymap) == 128, len(keymap)

out = []
out.append("""// General MIDI instruments for the OPL2, and the percussion key map.
//
// Generated by extract-gm-bank.py from audio/adlib.cpp of ScummVM
// (https://www.scummvm.org), whose AdLib driver carries these tables.
// ScummVM is free software under the GNU General Public License, version 3
// or (at your option) any later version; so is this file.
//
// Field encoding is ScummVM's: *Characteristic is register 0x20, *Level is
// register 0x40 (key scale in the top two bits, the instrument's own volume
// in the low six, 63 loudest), *AttackDecay and *SustainRelease are registers
// 0x60 and 0x80 stored inverted, *Waveform is register 0xe0 in its low two
// bits with the velocity sensitivity in the upper six, feedback is register
// 0xc0, and duration (percussion) is how long the note rings.
#ifndef OPL_GM_BANK_H
#define OPL_GM_BANK_H

#include <stdint.h>

namespace OplMidi {

struct Patch {
	uint8_t modCharacteristic, modLevel, modAttackDecay, modSustainRelease, modWaveform;
	uint8_t carCharacteristic, carLevel, carAttackDecay, carSustainRelease, carWaveform;
	uint8_t feedback, duration;
};
""")


def emit(name, rows, count):
    out.append(f"static const Patch {name}[{count}] = {{")
    for i, row in enumerate(rows):
        # row: mod char, mod level, mod AD, mod SR, mod wave, car char, car level, car AD, car SR, car wave, feedback, duration
        out.append("\t{ " + ", ".join("0x%02x" % v for v in row) + " },")
    out.append("};\n")


emit("kGmMelodic", melodic, 128)
emit("kGmPercussion", percussion, 39)
out.append("// Percussion key (GM note) to kGmPercussion index; 0xff has no instrument.")
out.append("static const uint8_t kGmPercussionMap[128] = {")
for i in range(0, 128, 16):
    out.append("\t" + ", ".join("0x%02x" % v for v in keymap[i:i + 16]) + ",")
out.append("};\n")
out.append("} // namespace OplMidi\n\n#endif")
print("\n".join(out))
